repos:
-   repo: local
    hooks:
    -   id: yapf
        name: yapf
        stages: [commit]
        language: system
        entry: poetry run yapf -i -r .
        pass_filenames: false
        types: [python]
    -   id: ruff
        name: ruff
        stages: [commit]
        language: system
        entry: poetry run ruff check .
        pass_filenames: false
        types: [python]
    -   id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy .
        pass_filenames: false
    # -   id: pytest
    #     name: pytest
    #     stages: [commit]
    #     language: system
    #     entry: poetry run pytest tests
    #     pass_filenames: false
    -   id: poetry
        name: poetry
        stages: [commit]
        language: system
        entry: poetry lock --check
        pass_filenames: false